apiVersion: gobackup.io/v1
kind: Backup
metadata:
  name: example-backup
  namespace: gobackup-operator-test
model:
  backupModelRef:
    name: "example-backupmodel"
  storageRefs:
    - apiGroup: "gobackup.io"
      type: "S3"
      name: "example-s3"
      keep: 5
      timeout: 30
  databaseRefs:
    - apiGroup: "gobackup.io"
      type: "PostgreSQL"
      name: "example-postgresql"