apiVersion: gobackup.io/v1
kind: CronBackup
metadata:
  name: example-cronbackup
  namespace: gobackup-operator-test
backupModelRef:
  name: "example-backupmodel"
  schedule:
    cron: "* * * * *"
storageRefs:
  - apiGroup: "storage.gobackup.io"
    type: "S3"
    name: "example-s3"
    keep: 5
    timeout: 30
databaseRefs:
  - apiGroup: "database.gobackup.io"
    type: "PostgreSQL"
    name: "example-postgresql"