apiVersion: gobackup.io/v1
kind: Backup
metadata:
  name: example-backup
  namespace: gobackup-operator-test
backupModelRef:
  name: "example-backupmodel"
storageRefs:
  - apiGroup: "storage.gobackup.io"
    type: "S3"
    name: "example-s3"
    keep: 5
    timeout: 30
databaseRefs:
  - apiGroup: "database.gobackup.io"
    type: "PostgreSQL"
    name: "example-postgresql"