apiVersion: gobackup.io/v1
kind: BackupModel
metadata:
  name: example-backupmodel
  namespace: gobackup-operator-test
spec:
  description: "This is an example BackupModel"
  compressWith:
    type: "tar.gz"
  encodeWith:
    openssl: true
    salt: true
    base64: false
    password: "mysecretpassword"
    args: "-aes-256-cbc"
    cipher: "aes-256-cbc"
    type: "openssl"
  beforeScript: "echo 'Starting backup'"
  afterScript: "echo 'Backup completed'"