apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gobackup-operator-test
  name: gobackup-operator-role
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]