# permissions for end users to view backupmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backupmodel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backup-operator
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupmodel-viewer-role
rules:
- apiGroups:
  - backup.github.com
  resources:
  - backupmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.github.com
  resources:
  - backupmodels/status
  verbs:
  - get
