apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gobackup-operator-role-binding
  namespace: gobackup-operator-test
subjects:
- kind: ServiceAccount
  name: gobackup-operator-service-account
  namespace: gobackup-operator-test
roleRef:
  kind: ClusterRole
  name: gobackup-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io