# permissions for end users to edit influxdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gobackup-operator
    app.kubernetes.io/managed-by: kustomize
  name: influxdb-editor-role
rules:
- apiGroups:
  - gobackup.io
  resources:
  - influxdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - influxdbs/status
  verbs:
  - get
