# permissions for end users to edit postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresql-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gobackup-operator
    app.kubernetes.io/part-of: gobackup-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-editor-role
rules:
- apiGroups:
  - gobackup.io
  resources:
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - postgresqls/status
  verbs:
  - get
