# permissions for end users to edit postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresql-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backup-operator
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-editor-role
rules:
- apiGroups:
  - backup.github.com
  resources:
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.github.com
  resources:
  - postgresqls/status
  verbs:
  - get
