---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gobackup.gobackup.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.gobackup.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - gobackup.gobackup.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gobackup.io
  resources:
  - backupmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - backupmodels/finalizers
  verbs:
  - update
- apiGroups:
  - gobackup.io
  resources:
  - backupmodels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gobackup.io
  resources:
  - cronbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - cronbackups/finalizers
  verbs:
  - update
- apiGroups:
  - gobackup.io
  resources:
  - cronbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gobackup.io
  resources:
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - postgresqls/finalizers
  verbs:
  - update
- apiGroups:
  - gobackup.io
  resources:
  - postgresqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gobackup.io
  resources:
  - s3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - s3s/finalizers
  verbs:
  - update
- apiGroups:
  - gobackup.io
  resources:
  - s3s/status
  verbs:
  - get
  - patch
  - update
