---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.github.com
  resources:
  - backupmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.github.com
  resources:
  - backupmodels/finalizers
  verbs:
  - update
- apiGroups:
  - backup.github.com
  resources:
  - backupmodels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup.github.com
  resources:
  - cronbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.github.com
  resources:
  - cronbackups/finalizers
  verbs:
  - update
- apiGroups:
  - backup.github.com
  resources:
  - cronbackups/status
  verbs:
  - get
  - patch
  - update
