# permissions for end users to edit s3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: s3-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backup-operator
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3-editor-role
rules:
- apiGroups:
  - gobackup.io
  resources:
  - s3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gobackup.io
  resources:
  - s3s/status
  verbs:
  - get
