apiVersion: backup.github.com/v1
kind: CronBackup
metadata:
  labels:
    app.kubernetes.io/name: cronbackup
    app.kubernetes.io/instance: cronbackup-sample
    app.kubernetes.io/part-of: backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: backup-operator
  name: cronbackup-sample
spec:
  # TODO(user): Add fields here
