apiVersion: gobackup.io/v1
kind: BackupModel
metadata:
  labels:
    app.kubernetes.io/name: backupmodel
    app.kubernetes.io/instance: backupmodel-sample
    app.kubernetes.io/part-of: gobackup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gobackup-operator
  name: backupmodel-sample
spec:
  description: "This is an example BackupModel"
  compressWith:
    type: "tar.gz"
  encodeWith:
    openssl: true
    salt: true
    base64: false
    password: "mysecretpassword"
    args: "-aes-256-cbc"
    cipher: "aes-256-cbc"
    type: "openssl"
  beforeScript: "echo 'Starting backup'"
  afterScript: "echo 'Backup completed'"
