apiVersion: gobackup.io/v1
kind: CronBackup
metadata:
  labels:
    app.kubernetes.io/name: cronbackup
    app.kubernetes.io/instance: cronbackup-sample
    app.kubernetes.io/part-of: gobackup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gobackup-operator
  name: example-cronbackup
  namespace: default
backupModelRef:
  name: "your-backup-model"
  schedule:
    cron: "0 0 * * *"
    # every: "day"
    # at: "00:00"
storageRefs:
  - apiGroup: "gobackup.io"
    type: "S3"
    name: "example-s3"
    keep: 5
    timeout: 30
databaseRefs:
  - apiGroup: "gobackup.io"
    type: "MySQL"
    name: "example-mysql"