name: Go Lint
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  golint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.21
      id: go
    - name: Run golint
      run: make lint